---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: site-information.md
  label: Site Information
  read_only: false
- type: directory
  path: page-content
  label: Pages
  create: all
  match: "**/*"
upload_dir: public
public_path: "/public"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - NEXT_PUBLIC_MAPS_API_KEY=AIzaSyDyqtJUi4ldxfHmWeRmXu_OAtWvM6r3jF4
  - NEXT_PUBLIC_GA_ID=XXXXXXX
  preview_output_directory: ".next"
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:16
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
